raspberries:
  hosts:
    # km-pi0w-1.fritz.box:
    km-pi3b-1.fritz.box:
    km-pi4b-1.fritz.box:
    km-pi4b-2.fritz.box:
    km-pi4b-3.fritz.box:
    km-pi4b-4.fritz.box:
    km-pi4b-5.fritz.box:
  vars:
    ansible_user: pi

debian:
  children:
    raspberries:

docker:
  hosts:
    # km-pi0w-1.fritz.box:
    km-pi3b-1.fritz.box:
    km-pi4b-5.fritz.box:

kubernetes:
  hosts:
    km-pi4b-1.fritz.box:
    km-pi4b-2.fritz.box:
    km-pi4b-3.fritz.box:
    km-pi4b-4.fritz.box:
