raspberries:
  hosts:
    # km-pi0w-1.fritz.box:
    km-pi3b-1.fritz.box:
    km-pi4b-2.fritz.box:
    km-pi4b-3.fritz.box:
    km-pi4b-4.fritz.box:
    km-pi4b-8gb-e97bcc2c.fritz.box:
  vars:
    ansible_user: pi

docker:
  hosts:
    km-pi3b-1.fritz.box:
    km-pi4b-8gb-e97bcc2c.fritz.box:
