- name: baseline
  hosts: all
  roles:
    - baseline

- name: Raspberries
  hosts: raspberries
  become: true
  roles:
    - debian

- name: Docker
  hosts: docker
  become: true
  roles:
    - docker
