- name: baseline
  hosts: all
  roles:
    - baseline

- name: Debian
  hosts: debian
  become: true
  roles:
    - debian

- name: Docker
  hosts: docker
  become: true
  roles:
    - docker

- name: Kubernetes
  hosts: kubernetes
  become: true
  roles:
    - containerd
    - kubernetes
    - haproxy
