- name: Install baseline packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg
    - htop
    - ncdu
    - sudo
    - tig
    - tmux
    - vim
    - wget
