- name: Add download.docker.com apt repo
  deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg

- name: Install docker-ce package
  apt:
    name: docker-ce
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
